# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import camera_pb2 as camera__pb2


class CameraServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_camera = channel.unary_unary(
                '/CameraService/get_camera',
                request_serializer=camera__pb2.CameraRequest.SerializeToString,
                response_deserializer=camera__pb2.CameraData.FromString,
                )
        self.get_cameras = channel.unary_unary(
                '/CameraService/get_cameras',
                request_serializer=camera__pb2.CameraRequest.SerializeToString,
                response_deserializer=camera__pb2.CameraResponse.FromString,
                )


class CameraServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_camera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_cameras(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_camera': grpc.unary_unary_rpc_method_handler(
                    servicer.get_camera,
                    request_deserializer=camera__pb2.CameraRequest.FromString,
                    response_serializer=camera__pb2.CameraData.SerializeToString,
            ),
            'get_cameras': grpc.unary_unary_rpc_method_handler(
                    servicer.get_cameras,
                    request_deserializer=camera__pb2.CameraRequest.FromString,
                    response_serializer=camera__pb2.CameraResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CameraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CameraService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_camera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CameraService/get_camera',
            camera__pb2.CameraRequest.SerializeToString,
            camera__pb2.CameraData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_cameras(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CameraService/get_cameras',
            camera__pb2.CameraRequest.SerializeToString,
            camera__pb2.CameraResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
