# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63\x61mera.proto\"\x1b\n\rCameraRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"+\n\x0e\x43\x61meraResponse\x12\x19\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0b.CameraData\"5\n\x0e\x43\x61meraPosition\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\"\xaa\x01\n\nCameraData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12!\n\x08position\x18\x03 \x01(\x0b\x32\x0f.CameraPosition\x12\x14\n\x0crtsp_address\x18\x04 \x01(\t\x12\x11\n\trtsp_port\x18\x05 \x01(\x05\x12\x1a\n\x12rtsp_connection_id\x18\x06 \x01(\t\x12\x1a\n\x12rtsp_connection_pw\x18\x07 \x01(\t2n\n\rCameraService\x12+\n\nget_camera\x12\x0e.CameraRequest\x1a\x0b.CameraData\"\x00\x12\x30\n\x0bget_cameras\x12\x0e.CameraRequest\x1a\x0f.CameraResponse\"\x00\x62\x06proto3')



_CAMERAREQUEST = DESCRIPTOR.message_types_by_name['CameraRequest']
_CAMERARESPONSE = DESCRIPTOR.message_types_by_name['CameraResponse']
_CAMERAPOSITION = DESCRIPTOR.message_types_by_name['CameraPosition']
_CAMERADATA = DESCRIPTOR.message_types_by_name['CameraData']
CameraRequest = _reflection.GeneratedProtocolMessageType('CameraRequest', (_message.Message,), {
  'DESCRIPTOR' : _CAMERAREQUEST,
  '__module__' : 'camera_pb2'
  # @@protoc_insertion_point(class_scope:CameraRequest)
  })
_sym_db.RegisterMessage(CameraRequest)

CameraResponse = _reflection.GeneratedProtocolMessageType('CameraResponse', (_message.Message,), {
  'DESCRIPTOR' : _CAMERARESPONSE,
  '__module__' : 'camera_pb2'
  # @@protoc_insertion_point(class_scope:CameraResponse)
  })
_sym_db.RegisterMessage(CameraResponse)

CameraPosition = _reflection.GeneratedProtocolMessageType('CameraPosition', (_message.Message,), {
  'DESCRIPTOR' : _CAMERAPOSITION,
  '__module__' : 'camera_pb2'
  # @@protoc_insertion_point(class_scope:CameraPosition)
  })
_sym_db.RegisterMessage(CameraPosition)

CameraData = _reflection.GeneratedProtocolMessageType('CameraData', (_message.Message,), {
  'DESCRIPTOR' : _CAMERADATA,
  '__module__' : 'camera_pb2'
  # @@protoc_insertion_point(class_scope:CameraData)
  })
_sym_db.RegisterMessage(CameraData)

_CAMERASERVICE = DESCRIPTOR.services_by_name['CameraService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CAMERAREQUEST._serialized_start=16
  _CAMERAREQUEST._serialized_end=43
  _CAMERARESPONSE._serialized_start=45
  _CAMERARESPONSE._serialized_end=88
  _CAMERAPOSITION._serialized_start=90
  _CAMERAPOSITION._serialized_end=143
  _CAMERADATA._serialized_start=146
  _CAMERADATA._serialized_end=316
  _CAMERASERVICE._serialized_start=318
  _CAMERASERVICE._serialized_end=428
# @@protoc_insertion_point(module_scope)
