# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cobject.proto\"\x0f\n\rObjectRequest\"\x96\x01\n\nObjectData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.ObjectType\x12\x1a\n\x04\x62\x62ox\x18\x03 \x01(\x0b\x32\x0c.BoundingBox\x12\x1f\n\ntrajectory\x18\x04 \x03(\x0b\x32\x0b.Coordinate\x12$\n\x0fprediction_path\x18\x05 \x03(\x0b\x32\x0b.Coordinate\"B\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\"\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02*5\n\nObjectType\x12\x07\n\x03\x43\x61r\x10\x00\x12\x07\n\x03\x42us\x10\x01\x12\t\n\x05Truck\x10\x02\x12\n\n\x06Person\x10\x03\x32\x44\n\rObjectService\x12\x33\n\x10streaming_object\x12\x0e.ObjectRequest\x1a\x0b.ObjectData\"\x00\x30\x01\x62\x06proto3')

_OBJECTTYPE = DESCRIPTOR.enum_types_by_name['ObjectType']
ObjectType = enum_type_wrapper.EnumTypeWrapper(_OBJECTTYPE)
Car = 0
Bus = 1
Truck = 2
Person = 3


_OBJECTREQUEST = DESCRIPTOR.message_types_by_name['ObjectRequest']
_OBJECTDATA = DESCRIPTOR.message_types_by_name['ObjectData']
_BOUNDINGBOX = DESCRIPTOR.message_types_by_name['BoundingBox']
_COORDINATE = DESCRIPTOR.message_types_by_name['Coordinate']
ObjectRequest = _reflection.GeneratedProtocolMessageType('ObjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTREQUEST,
  '__module__' : 'object_pb2'
  # @@protoc_insertion_point(class_scope:ObjectRequest)
  })
_sym_db.RegisterMessage(ObjectRequest)

ObjectData = _reflection.GeneratedProtocolMessageType('ObjectData', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTDATA,
  '__module__' : 'object_pb2'
  # @@protoc_insertion_point(class_scope:ObjectData)
  })
_sym_db.RegisterMessage(ObjectData)

BoundingBox = _reflection.GeneratedProtocolMessageType('BoundingBox', (_message.Message,), {
  'DESCRIPTOR' : _BOUNDINGBOX,
  '__module__' : 'object_pb2'
  # @@protoc_insertion_point(class_scope:BoundingBox)
  })
_sym_db.RegisterMessage(BoundingBox)

Coordinate = _reflection.GeneratedProtocolMessageType('Coordinate', (_message.Message,), {
  'DESCRIPTOR' : _COORDINATE,
  '__module__' : 'object_pb2'
  # @@protoc_insertion_point(class_scope:Coordinate)
  })
_sym_db.RegisterMessage(Coordinate)

_OBJECTSERVICE = DESCRIPTOR.services_by_name['ObjectService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJECTTYPE._serialized_start=290
  _OBJECTTYPE._serialized_end=343
  _OBJECTREQUEST._serialized_start=16
  _OBJECTREQUEST._serialized_end=31
  _OBJECTDATA._serialized_start=34
  _OBJECTDATA._serialized_end=184
  _BOUNDINGBOX._serialized_start=186
  _BOUNDINGBOX._serialized_end=252
  _COORDINATE._serialized_start=254
  _COORDINATE._serialized_end=288
  _OBJECTSERVICE._serialized_start=345
  _OBJECTSERVICE._serialized_end=413
# @@protoc_insertion_point(module_scope)
