# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='object.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cobject.proto\"\x0f\n\rObjectRequest\"\x92\x01\n\nObjectData\x12\n\n\x02id\x18\x01 \x01(\x05\x12%\n\ncoordinate\x18\x02 \x01(\x0b\x32\x11.ObjectCoordinate\x12%\n\ntrajectory\x18\x03 \x03(\x0b\x32\x11.ObjectCoordinate\x12*\n\x0fprediction_path\x18\x04 \x03(\x0b\x32\x11.ObjectCoordinate\"(\n\x10ObjectCoordinate\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x32\x44\n\rObjectService\x12\x33\n\x10streaming_object\x12\x0e.ObjectRequest\x1a\x0b.ObjectData\"\x00\x30\x01\x62\x06proto3'
)




_OBJECTREQUEST = _descriptor.Descriptor(
  name='ObjectRequest',
  full_name='ObjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=31,
)


_OBJECTDATA = _descriptor.Descriptor(
  name='ObjectData',
  full_name='ObjectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ObjectData.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='ObjectData.coordinate', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trajectory', full_name='ObjectData.trajectory', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prediction_path', full_name='ObjectData.prediction_path', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=180,
)


_OBJECTCOORDINATE = _descriptor.Descriptor(
  name='ObjectCoordinate',
  full_name='ObjectCoordinate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='ObjectCoordinate.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='ObjectCoordinate.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=222,
)

_OBJECTDATA.fields_by_name['coordinate'].message_type = _OBJECTCOORDINATE
_OBJECTDATA.fields_by_name['trajectory'].message_type = _OBJECTCOORDINATE
_OBJECTDATA.fields_by_name['prediction_path'].message_type = _OBJECTCOORDINATE
DESCRIPTOR.message_types_by_name['ObjectRequest'] = _OBJECTREQUEST
DESCRIPTOR.message_types_by_name['ObjectData'] = _OBJECTDATA
DESCRIPTOR.message_types_by_name['ObjectCoordinate'] = _OBJECTCOORDINATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObjectRequest = _reflection.GeneratedProtocolMessageType('ObjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTREQUEST,
  '__module__' : 'object_pb2'
  # @@protoc_insertion_point(class_scope:ObjectRequest)
  })
_sym_db.RegisterMessage(ObjectRequest)

ObjectData = _reflection.GeneratedProtocolMessageType('ObjectData', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTDATA,
  '__module__' : 'object_pb2'
  # @@protoc_insertion_point(class_scope:ObjectData)
  })
_sym_db.RegisterMessage(ObjectData)

ObjectCoordinate = _reflection.GeneratedProtocolMessageType('ObjectCoordinate', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTCOORDINATE,
  '__module__' : 'object_pb2'
  # @@protoc_insertion_point(class_scope:ObjectCoordinate)
  })
_sym_db.RegisterMessage(ObjectCoordinate)



_OBJECTSERVICE = _descriptor.ServiceDescriptor(
  name='ObjectService',
  full_name='ObjectService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=224,
  serialized_end=292,
  methods=[
  _descriptor.MethodDescriptor(
    name='streaming_object',
    full_name='ObjectService.streaming_object',
    index=0,
    containing_service=None,
    input_type=_OBJECTREQUEST,
    output_type=_OBJECTDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OBJECTSERVICE)

DESCRIPTOR.services_by_name['ObjectService'] = _OBJECTSERVICE

# @@protoc_insertion_point(module_scope)
