# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scenario.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scenario.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0escenario.proto\"\x1d\n\x0fScenarioRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"/\n\x10ScenarioResponse\x12\x1b\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\r.ScenarioData\"7\n\x0cScenarioData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1b\n\x04type\x18\x02 \x01(\x0e\x32\r.ScenarioType*\x1c\n\x0cScenarioType\x12\x0c\n\x08\x41\x43\x43IDENT\x10\x00\x32|\n\x0fScenarioService\x12\x31\n\x0cget_scenario\x12\x10.ScenarioRequest\x1a\r.ScenarioData\"\x00\x12\x36\n\rget_scenarios\x12\x10.ScenarioRequest\x1a\x11.ScenarioResponse\"\x00\x62\x06proto3'
)

_SCENARIOTYPE = _descriptor.EnumDescriptor(
  name='ScenarioType',
  full_name='ScenarioType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACCIDENT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=155,
  serialized_end=183,
)
_sym_db.RegisterEnumDescriptor(_SCENARIOTYPE)

ScenarioType = enum_type_wrapper.EnumTypeWrapper(_SCENARIOTYPE)
ACCIDENT = 0



_SCENARIOREQUEST = _descriptor.Descriptor(
  name='ScenarioRequest',
  full_name='ScenarioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ScenarioRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=47,
)


_SCENARIORESPONSE = _descriptor.Descriptor(
  name='ScenarioResponse',
  full_name='ScenarioResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ScenarioResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=96,
)


_SCENARIODATA = _descriptor.Descriptor(
  name='ScenarioData',
  full_name='ScenarioData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ScenarioData.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='ScenarioData.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=153,
)

_SCENARIORESPONSE.fields_by_name['data'].message_type = _SCENARIODATA
_SCENARIODATA.fields_by_name['type'].enum_type = _SCENARIOTYPE
DESCRIPTOR.message_types_by_name['ScenarioRequest'] = _SCENARIOREQUEST
DESCRIPTOR.message_types_by_name['ScenarioResponse'] = _SCENARIORESPONSE
DESCRIPTOR.message_types_by_name['ScenarioData'] = _SCENARIODATA
DESCRIPTOR.enum_types_by_name['ScenarioType'] = _SCENARIOTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScenarioRequest = _reflection.GeneratedProtocolMessageType('ScenarioRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCENARIOREQUEST,
  '__module__' : 'scenario_pb2'
  # @@protoc_insertion_point(class_scope:ScenarioRequest)
  })
_sym_db.RegisterMessage(ScenarioRequest)

ScenarioResponse = _reflection.GeneratedProtocolMessageType('ScenarioResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCENARIORESPONSE,
  '__module__' : 'scenario_pb2'
  # @@protoc_insertion_point(class_scope:ScenarioResponse)
  })
_sym_db.RegisterMessage(ScenarioResponse)

ScenarioData = _reflection.GeneratedProtocolMessageType('ScenarioData', (_message.Message,), {
  'DESCRIPTOR' : _SCENARIODATA,
  '__module__' : 'scenario_pb2'
  # @@protoc_insertion_point(class_scope:ScenarioData)
  })
_sym_db.RegisterMessage(ScenarioData)



_SCENARIOSERVICE = _descriptor.ServiceDescriptor(
  name='ScenarioService',
  full_name='ScenarioService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=185,
  serialized_end=309,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_scenario',
    full_name='ScenarioService.get_scenario',
    index=0,
    containing_service=None,
    input_type=_SCENARIOREQUEST,
    output_type=_SCENARIODATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_scenarios',
    full_name='ScenarioService.get_scenarios',
    index=1,
    containing_service=None,
    input_type=_SCENARIOREQUEST,
    output_type=_SCENARIORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCENARIOSERVICE)

DESCRIPTOR.services_by_name['ScenarioService'] = _SCENARIOSERVICE

# @@protoc_insertion_point(module_scope)
