# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scenario.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0escenario.proto*\x1c\n\x0cScenarioType\x12\x0c\n\x08\x41\x43\x43IDENT\x10\x00\x62\x06proto3')

_SCENARIOTYPE = DESCRIPTOR.enum_types_by_name['ScenarioType']
ScenarioType = enum_type_wrapper.EnumTypeWrapper(_SCENARIOTYPE)
ACCIDENT = 0


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENARIOTYPE._serialized_start=18
  _SCENARIOTYPE._serialized_end=46
# @@protoc_insertion_point(module_scope)
