# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import scenario_pb2 as scenario__pb2


class ScenarioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_scenario = channel.unary_unary(
                '/ScenarioService/get_scenario',
                request_serializer=scenario__pb2.ScenarioRequest.SerializeToString,
                response_deserializer=scenario__pb2.ScenarioData.FromString,
                )
        self.get_scenarios = channel.unary_unary(
                '/ScenarioService/get_scenarios',
                request_serializer=scenario__pb2.ScenarioRequest.SerializeToString,
                response_deserializer=scenario__pb2.ScenarioResponse.FromString,
                )


class ScenarioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_scenario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_scenarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScenarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_scenario': grpc.unary_unary_rpc_method_handler(
                    servicer.get_scenario,
                    request_deserializer=scenario__pb2.ScenarioRequest.FromString,
                    response_serializer=scenario__pb2.ScenarioData.SerializeToString,
            ),
            'get_scenarios': grpc.unary_unary_rpc_method_handler(
                    servicer.get_scenarios,
                    request_deserializer=scenario__pb2.ScenarioRequest.FromString,
                    response_serializer=scenario__pb2.ScenarioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ScenarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ScenarioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_scenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ScenarioService/get_scenario',
            scenario__pb2.ScenarioRequest.SerializeToString,
            scenario__pb2.ScenarioData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_scenarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ScenarioService/get_scenarios',
            scenario__pb2.ScenarioRequest.SerializeToString,
            scenario__pb2.ScenarioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
