# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\'\n\x0bTestRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"E\n\x0cTestResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\n\n\x02li\x18\x04 \x03(\x05\x32j\n\x0bTestService\x12(\n\x07request\x12\x0c.TestRequest\x1a\r.TestResponse\"\x00\x12\x31\n\x0erequest_stream\x12\x0c.TestRequest\x1a\r.TestResponse\"\x00\x30\x01\x62\x06proto3')



_TESTREQUEST = DESCRIPTOR.message_types_by_name['TestRequest']
_TESTRESPONSE = DESCRIPTOR.message_types_by_name['TestResponse']
TestRequest = _reflection.GeneratedProtocolMessageType('TestRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:TestRequest)
  })
_sym_db.RegisterMessage(TestRequest)

TestResponse = _reflection.GeneratedProtocolMessageType('TestResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTRESPONSE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:TestResponse)
  })
_sym_db.RegisterMessage(TestResponse)

_TESTSERVICE = DESCRIPTOR.services_by_name['TestService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTREQUEST._serialized_start=14
  _TESTREQUEST._serialized_end=53
  _TESTRESPONSE._serialized_start=55
  _TESTRESPONSE._serialized_end=124
  _TESTSERVICE._serialized_start=126
  _TESTSERVICE._serialized_end=232
# @@protoc_insertion_point(module_scope)
